name = "logistic"
uuid = "a435d4c5-ebd0-4d5f-8ca2-f082ff3a8f9e"
authors = ["Ryosuke Suda "]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
